import "@/styles/globals.css"
import { MoralisProvider } from "react-moralis"
import Header from "../components/header"
import Head from "next/head"

export default function App({ Component, pageProps }) {
    return (
        <div>
            <Head>
                <title> NoRug NFT Marketplace</title>
                <meta
                    name="NoRug NFT Marketplace"
                    content="Generated by 0xdong"
                />
            </Head>
            <MoralisProvider initializeOnMount={false}>
                <Header />
                <Component {...pageProps} />
            </MoralisProvider>
        </div>
    )
}
