import Head from "next/head"

import styles from "@/styles/Home.module.css"

export default function Sell() {
    return (
        <>
            <Head>
                <title> Sell page </title>
                <meta
                    name="NoRug NFT Marketplace"
                    content="Generated by 0xdong"
                />
            </Head>
            hi! sell page
        </>
    )
}
